bcmagic/urls.py
from __future__ import unicode_literals
from django.urls import path

from bcmagic.views import (
    json_test,
    magic,
    index,
)

urlpatterns = [
    path("", index, name="bcmagic_index"),
    path("json_test/", json_test, name="bcmagic_json_test"),
    path("magic/", magic, name="bcmagic_index"),
]

ga_frontend/urls.py
from django.conf.urls.defaults import *

# Databrowser:
from django.contrib import databrowse
from fctracker.models import Library, FlowCell
databrowse.site.register(Library)
databrowse.site.register(FlowCell)

urlpatterns = patterns('',
    # Base:
    (r'^eland_config/', include('ga_frontend.eland_config.urls')),
    # Admin:
     (r'^admin/', include('django.contrib.admin.urls')),
    # Databrowser:
     (r'^databrowse/(.*)', databrowse.site.root),
)

htsworkflow/urls.py
from django.urls import include, path
from django.contrib import admin

from experiments.views import (
    FlowCellListView,
    flowcell_lane_detail,
    flowcell_detail,
    lanes_for,
    sequencer,
)
from samples.views import library_id_to_admin_url

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    # Base:
    path("eland_config/", include("eland_config.urls")),
    # Experiments:
    path("experiments/", include("experiments.urls")),
    path("lane/<lane_pk>", flowcell_lane_detail, name="flowcell_lane_detail"),
    path("flowcell/<flowcell_id>/", flowcell_detail, name="flowcell_detail"),
    path(
        "flowcell/<flowcell_id>/<lane_number>/",
        flowcell_detail,
        name="flowcell_detail",
    ),
    path("flowcell/", FlowCellListView.as_view(), name="flowcell_index"),
    path("inventory/", include("inventory.urls")),
    path("library/", include("samples.urls")),
    path("lanes_for/", lanes_for, name="lanes_for"),
    path("lanes_for/<username>", lanes_for, name="lanes_for"),
    ### library id to admin url
    path("library_id_to_admin_url/<library_id>/", library_id_to_admin_url),
    path("sequencer/<sequencer_id>", sequencer, name="sequencer"),
    path("admin/", admin.site.urls),
]

samples/urls.py
from __future__ import unicode_literals

from django.urls import path

from samples.views import (
    library_index,
    library_not_run,
    library_detail,
    library_json,
    species_json,
    species,
    antibodies,
)

urlpatterns = [
    # View library list
    path("", library_index, name="library_index"),
    path("not_run/", library_not_run, name="library_not_run"),
    path("<library_id>/", library_detail, name="library_detail"),
    path("<library_id>/json", library_json, name="library_json"),
    path("species/<species_id>/json", species_json, name="species_json"),
    path("species/<species_id>", species, name="species"),
    path("antibody/", antibodies, name="antibodies"),
]

samples/models.py
from __future__ import unicode_literals

import logging
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.db.models.signals import post_save
from django.db import connection
from django.core.validators import RegexValidator
import six

logger = logging.getLogger(__name__)


class AccessionAgency(models.Model):
    """An organization one submits data to
    """
    name = models.CharField(max_length=255)
    homepage = models.URLField(blank=True)
    library_template = models.URLField(blank=True)

    class Meta:
        verbose_name_plural = 'Accession Agencies'

    def __str__(self):
        return self.name


class Accession(models.Model):
    """Track accession IDs assigned to our objects.
    """
    accession = models.CharField(
        max_length=255,
        db_index=True,
        validators=[RegexValidator(
            "^[-A-Za-z0-9:.]*$",
            message="Please only use letters, digits, and :.-")]
    )
    url = models.URLField(blank=True, null=True)
    agency = models.ForeignKey(AccessionAgency, on_delete=models.CASCADE)
    created = models.DateTimeField()

    class Meta:
        abstract = True

    def update_url(self, template):
        if template and not self.url:
            self.url = template.format(self.accession)

    def __str__(self):
        return str(self.agency) + ":" + self.accession


class LibraryAccession(Accession):
    library = models.ForeignKey('Library', on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.update_url(self.agency.library_template)
        super(LibraryAccession, self).save(*args, **kwargs)


class Antibody(models.Model):
    antigene = models.CharField(max_length=500, db_index=True)
    # New field Aug/20/08
    # SQL to add column:
    # alter table fctracker_antibody add column "nickname" varchar(20) NULL;
    nickname = models.CharField(
        max_length=20,
        blank=True,
        null=True,
        db_index=True
    )
    catalog = models.CharField(max_length=50, blank=True, null=True)
    antibodies = models.CharField(max_length=500, db_index=True)
    source = models.CharField(max_length=500,
                              blank=True, null=True, db_index=True)
    biology = models.TextField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return '%s - %s' % (self.antigene, self.antibodies)

    class Meta:
        verbose_name_plural = "antibodies"
        ordering = ["antigene"]


class Cellline(models.Model):
    cellline_name = models.CharField(max_length=100,
                                     unique=True, db_index=True)
    nickname = models.CharField(
        max_length=20,
        blank=True,
        null=True,
        db_index=True)

    notes = models.TextField(blank=True)

    def __str__(self):
        return str(self.cellline_name)

    class Meta:
        ordering = ["cellline_name"]


class Condition(models.Model):
    condition_name = models.CharField(
        max_length=2000, unique=True, db_index=True)
    nickname = models.CharField(
        max_length=20,
        blank=True,
        null=True,
        db_index=True,
        verbose_name='Short Name')
    notes = models.TextField(blank=True)

    def __str__(self):
        return str(self.condition_name)

    class Meta:
        ordering = ["condition_name"]


class ExperimentType(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return str(self.name)


class Tag(models.Model):
    tag_name = models.CharField(max_length=100,
                                db_index=True, blank=False, null=False)
    TAG_CONTEXT = (
        # ('Antibody','Antibody'),
        # ('Cellline', 'Cellline'),
        # ('Condition', 'Condition'),
        ('Library', 'Library'),
        ('ANY', 'ANY'),
    )
    context = models.CharField(
        max_length=50,
        choices=TAG_CONTEXT, default='Library')

    def __str__(self):
        return '%s' % (self.tag_name,)

    class Meta:
        ordering = ["context", "tag_name"]


class Species(models.Model):
    scientific_name = models.CharField(
        max_length=256,
        unique=False,
        db_index=True
    )
    common_name = models.CharField(max_length=256, blank=True)

    def __str__(self):
        return '%s (%s)' % (self.scientific_name, self.common_name)

    class Meta:
        verbose_name_plural = "species"
        ordering = ["scientific_name"]

    def get_absolute_url(self):
        return reverse('species', kwargs={'species_id': str(self.id)})


class Affiliation(models.Model):
    name = models.CharField(max_length=256, db_index=True, verbose_name='Name')
    contact = models.CharField(max_length=256,
                               null=True, blank=True, verbose_name='Lab Name')
    email = models.EmailField(null=True, blank=True)
    users = models.ManyToManyField('HTSUser', blank=True)
    users.admin_order_field = "username"

    def __str__(self):
        name = str(self.name)
        if self.contact is not None and len(self.contact) > 0:
            name += ' ('+self.contact+')'
        return name

    def Users(self):
        users = self.users.all().order_by('username')
        return ", ".join([str(a) for a in users])

    class Meta:
        ordering = ["name", "contact"]
        unique_together = (("name", "contact"),)


class LibraryType(models.Model):
    name = models.CharField(max_length=255, unique=True,
                            verbose_name="Adapter Type")
    is_paired_end = models.BooleanField(
        default=True,
        help_text="can you do a paired end run with this adapter")
    can_multiplex = models.BooleanField(
        default=True,
        help_text="Does this adapter provide multiplexing?")

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ["-id"]


class MultiplexIndex(models.Model):
    """Map adapter types to the multiplex sequence"""
    adapter_type = models.ForeignKey(LibraryType, on_delete=models.CASCADE)
    multiplex_id = models.CharField(max_length=6, null=False)
    sequence = models.CharField(max_length=12, blank=True, null=True)

    class Meta:
        verbose_name_plural = "multiplex indicies"
        unique_together = ('adapter_type', 'multiplex_id')


def validate_multiplex_index(value):
    for element in value.split(","):
        fields = element.split("-")
        if len(fields) > 2:
            raise ValidationError(
                "MultiplexIndex ids can only be a comma sperated list of value or "
                "value-value. {} seems invalid".format(element))


class Library(models.Model):
    id = models.CharField(max_length=10, primary_key=True)
    library_name = models.CharField(max_length=100, unique=True)
    library_species = models.ForeignKey(Species, on_delete=models.CASCADE)
    hidden = models.BooleanField(default=False)
    account_number = models.CharField(max_length=100, null=True, blank=True)
    cell_line = models.ForeignKey(Cellline, blank=True, null=True,
                                  verbose_name="Background",
                                  on_delete=models.CASCADE)
    condition = models.ForeignKey(Condition, blank=True, null=True, on_delete=models.CASCADE)
    antibody = models.ForeignKey(Antibody, blank=True, null=True, on_delete=models.CASCADE)
    affiliations = models.ManyToManyField(
        Affiliation, related_name='library_affiliations')
    tags = models.ManyToManyField(Tag, related_name='library_tags',
                                  blank=True)
    REPLICATE_NUM = [(x, x) for x in range(1, 7)]
    replicate = models.PositiveSmallIntegerField(choices=REPLICATE_NUM,
                                                 blank=True, null=True)
    experiment_type = models.ForeignKey(ExperimentType, on_delete=models.CASCADE)
    library_type = models.ForeignKey(LibraryType, blank=True, null=True,
                                     verbose_name="Adapter Type",
                                     on_delete=models.CASCADE)
    multiplex_id = models.CharField(max_length=255,
                                    blank=True, null=True,
                                    verbose_name="Index ID",
                                    validators=[validate_multiplex_index])
    creation_date = models.DateField(blank=True, null=True)
    made_for = models.CharField(max_length=50, blank=True,
                                verbose_name='ChIP/DNA/RNA Made By')
    made_by = models.CharField(max_length=50, blank=True, default="Lorian")

    PROTOCOL_END_POINTS = (
        ('?', 'Unknown'),
        ('Sample', 'Raw sample'),
        ('Progress', 'In progress'),
        ('1A', 'Ligation, then gel'),
        ('PCR', 'Ligation, then PCR'),
        ('1Ab', 'Ligation, PCR, then gel'),
        ('1Ac', 'Ligation, gel, then 12x PCR'),
        ('1Aa', 'Ligation, gel, then 18x PCR'),
        ('2A', 'Ligation, PCR, gel, PCR'),
        ('Done', 'Completed'),
    )
    PROTOCOL_END_POINTS_DICT = dict(PROTOCOL_END_POINTS)
    stopping_point = models.CharField(max_length=25,
                                      choices=PROTOCOL_END_POINTS,
                                      default='Done')

    amplified_from_sample = models.ForeignKey(
        'self',
        related_name='amplified_into_sample',
        blank=True, null=True,
        on_delete=models.CASCADE
    )

    undiluted_concentration = models.DecimalField(
        "Concentration",
        max_digits=5, decimal_places=2, blank=True, null=True,
        help_text="Undiluted concentration (ng/\u00b5l)")
    # note \u00b5 is the micro symbol in unicode
    successful_pM = models.DecimalField(
        max_digits=9, decimal_places=1, blank=True, null=True)
    ten_nM_dilution = models.BooleanField(default=False)
    gel_cut_size = models.IntegerField(default=225, blank=True, null=True)

trunk/htsworkflow/frontend/experiments/views.py
# Create your views here.
#from django.template import Context, loader
#shortcut to the above modules
from django.shortcuts import render_to_response, get_object_or_404
from htsworkflow.frontend.experiments.models import *
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist

def index(request):
    all_runs = DataRun.objects.order_by('-run_start_time')
    #t = loader.get_template('experiments/index.html')
    #c = Context({
    #    'data_run_list': all_runs,
    #})
    #return HttpResponse(t.render(c)) 
    # shortcut to the above module usage
    return render_to_response('experiments/index.html',{'data_run_list': all_runs}) 
    
def detail(request, run_folder):
    html_str = '<h2>Exp Track Details Page</h2>'
    html_str += 'Run Folder: '+run_folder
    r = get_object_or_404(DataRun,run_folder=run_folder)
    return render_to_response('experiments/detail.html',{'run_f': r})

def makeFCSheet(request,fcid):
  # get Flowcell by input fcid
  # ...
  rec = None
  try:
    rec = FlowCell.objects.get(flowcell_id=fcid)
  except ObjectDoesNotExist:
    pass
  lanes = ['1','2','3','4','5','6','7','8']
  return render_to_response('experiments/flowcellSheet.html',{'fc': rec})

trunk/htsworkflow/frontend/inventory/views.py
from htsworkflow.frontend.inventory.models import Item, LongTermStorage
from htsworkflow.frontend.experiments.models import FlowCell

from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse


def link_flowcell_and_device(request, flowcell, serial):
    """
    Updates database records of a flowcell being archived on a device with a particular serial #
    """
    assert flowcell is not None
    assert serial is not None
    
    LTS_UPDATED = False
    SD_UPDATED = False
    LIBRARY_UPDATED = False
        
    ###########################################
    # Retrieve Storage Device
    try:
        sd = Item.objects.get(barcode_id=serial)
    except ObjectDoesNotExist, e:
        msg = "Item with barcode_id of %s not found." % (serial)
        raise ObjectDoesNotExist(msg)
    
    ###########################################
    # Retrieve FlowCell
    try:    
        fc = FlowCell.objects.get(flowcell_id=flowcell)
    except ObjectDoesNotExist, e:
        msg = "FlowCell with flowcell_id of %s not found." % (flowcell)
        raise ObjectDoesNotExist(msg)
    
    ###########################################
    # Retrieve or create LongTermStorage Object
    count = fc.longtermstorage_set.count()
    lts = None
    if count > 1:
        msg = "There really should only be one longtermstorage object per flowcell"
        raise ValueError, msg
    elif count == 1:
        # lts already attached to flowcell
        lts = fc.longtermstorage_set.all()[0]
    else:
        lts = LongTermStorage()
        # Attach flowcell
        lts.flowcell = fc
        # Need a primary keey before linking to storage devices
        lts.save()
        LTS_UPDATED = True
        
        
    ############################################
    # Link Storage to Flowcell
    
    # Add a link to this storage device if it is not already linked.
    if sd not in lts.storage_devices.all():
        lts.storage_devices.add(sd)
        SD_UPDATED = True
    
    ###########################################
    # Add Library Links to LTS
    
    if fc.lane_1_library not in lts.libraries.all():
        lts.libraries.add(fc.lane_1_library)
        LIBRARY_UPDATED = True
        print 1
    
    if fc.lane_2_library not in lts.libraries.all():
        lts.libraries.add(fc.lane_2_library)
        LIBRARY_UPDATED = True
        print 2
    
    if fc.lane_3_library not in lts.libraries.all():
        lts.libraries.add(fc.lane_3_library)
        LIBRARY_UPDATED = True
        print 3
    
    if fc.lane_4_library not in lts.libraries.all():
        lts.libraries.add(fc.lane_4_library)
        LIBRARY_UPDATED = True
        print 4
    
    
    if fc.lane_5_library not in lts.libraries.all():
        lts.libraries.add(fc.lane_5_library)
        LIBRARY_UPDATED = True
        print 5
    
    if fc.lane_6_library not in lts.libraries.all():
        lts.libraries.add(fc.lane_6_library)
        LIBRARY_UPDATED = True
        print 6
    
    if fc.lane_7_library not in lts.libraries.all():
        lts.libraries.add(fc.lane_7_library)
        LIBRARY_UPDATED = True
        print 7
    
    if fc.lane_8_library not in lts.libraries.all():
        lts.libraries.add(fc.lane_8_library)
        LIBRARY_UPDATED = True
        print 8
        
    # Save Changes
    lts.save()
    
    msg = ['Success:']
    if LTS_UPDATED or SD_UPDATED or LIBRARY_UPDATED:
        msg.append('  LongTermStorage (LTS) Created: %s' % (LTS_UPDATED))
        msg.append('   Storage Device Linked to LTS: %s' % (SD_UPDATED))
        msg.append('       Libraries updated in LTS: %s' % (LIBRARY_UPDATED))
    else:
        msg.append('  No Updates Needed.')
    
    return HttpResponse('\n'.join(msg))

htsworkflow/templates/samples/antibody_index.html
{% extends "base_site.html" %}
{% load admin_list i18n %}

{% block bodyclass %}change-list{% endblock %}
{% block coltype %}flex{% endblock %}

{% block content %}
<div id="antibody-index-div">
{% block body %}
<table >
  <thead >
    <tr >
      <td >Antigene</td>
      <td >Nickname</td>
      <td >Antibodies</td>
      <td >Catalog</td>
      <td >Source</td>
  </tr>
  </thead>
  <tbody >
    {% for antibody in antibodies %}
    <tr >
      <td >
        {{ antibody.antigene }}
      </td>
      <td >
        {{ antibody.nickname }}
      </td>
      <td >
        {{ antibody.antibodies }}
      </td>
      <td >
        {{ antibody.catalog }}
      </td>
      <td >
        {{ antibody.source }}
      </td>
   </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% endblock %}
{% endblock %}

htsworkflow/templates/samples/lanes_for.html
{% extends "base_site.html" %}
{% load admin_list i18n %}

{% block bodyclass %}change-list{% endblock %}
{% block coltype %}flex{% endblock %}

{% block content %}
<div id="lanes-index-div">
  <div class="module{% if cl.has_filters %} filtered{% endif %}" id="changelist">
    {% block search %}{% search_form lanes %}{% endblock %}

    {% block filters %}
    {% if lanes.has_filters %}
    <div id="changelist-filter">
      <h2 >{% translate 'Filter' %}</h2>
      {% for spec in lanes.filter_specs %}
         {% admin_list_filter lanes spec %}
      {% endfor %}
    </div>
    {% endif %}
    {% endblock %}

  
  {% block pagination %}{% pagination lanes %}{% endblock %}

  {% block body %}
  <table >
    <thead >
      <tr >
        <td >Run Date</td>
        <td >Flowcell Type</td>
        <td >Cycles</td>
        <td >Flowcell ID</td>
        <td >Lane</td>
        <td >Library ID</td>
        <td >Library Name</td>
    </tr>
    </thead>
    <tbody >
      {% for lane in lanes.queryset %}
      <tr >
        <td >
          {{ lane.flowcell.run_date|date:"Y-M-d" }}
        </td>
        <td >
          {{ lane.flowcell.flowcell_type }}
        </td>
        <td >
          {{ lane.flowcell.read_length }}
        </td>
        <td >
          {{ lane.flowcell.flowcell_id }}
        </td>
        <td >
          {{ lane.lane_number }}
        </td>
        <td >
          <a href="/library/{{ lane.library_id }}">{{ lane.library_id }}</a>
        </td>
        <td >
          <a href="/library/{{ lane.library_id }}">{{ lane.library.library_name }}</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  </div>
  {% endblock %}
</div>
{% endblock %}

htsworkflow/templates/samples/library_index.html
{% extends "base_site.html" %}
{% load admin_list i18n %}
{% load static %}
{% block extrahead %}
    <!-- App Stuff -->
    <link type="text/css" rel="stylesheet" href="{% static "css/app.css" %}"/>

    {% block additional_javascript %}
    <script type="text/javascript" src="{% static "js/htsw.js" %}"></script>
    {% endblock %}
{% endblock %}
{% block bodyclass %}change-list{% endblock %}
{% block coltype %}flex{% endblock %}

{% block content %}
<div id="library_header_link">
{% if todo_only %}<a href="..">All</a>{% else %}<a href="not_run/">Not run</a>
{% endif %}
</div>
<div id="library-index-div" >
  <div class="module{% if cl.has_filters %} filtered{% endif %}" id="changelist">
    {% block search %}{% search_form cl %}{% endblock %}

    {% block pagination %}{% pagination cl %}{% endblock %}

    {% block filters %}
    {% if cl.has_filters %}
    <div id="changelist-filter">
      <h2 >{% translate 'Filter' %}</h2>
      {% for spec in cl.filter_specs %}
         {% admin_list_filter cl spec %}
         {% endfor %}
    </div>
    {% endif %}
    {% endblock %}
  {% block summary_stats %}
  <table class="{% if cl.has_filters %} filtered{% endif %}">
    <thead >
      <tr >
        <td >Parent</td>
        <td >Library ID</td>
        <td >Species</td>
        <td >Library Name</td>
        <td colspan="3" >Single</td>
        <td colspan="3" >Paired</td>
        <td >HD</td>
      </tr>
      <tr >
        <td colspan="4"></td>
        <td>&lt;40</td>
        <td>&lt;100</td>
        <td>100+</td>
        <td>&lt;40</td>
        <td>&lt;100</td>
        <td>100+</td>
        <td></td>
      </tr>
    </thead>
    <tbody >
      {% for lib in library_list %}
      <tr typeof="libns:Library" about="{{lib.get_absolute_url}}">
        <td >
          <a href="{{lib.amplified_from_sample.get_absolute_url }}">
            {{ lib.amplified_from_sample.id }}
          </a>
        </td>
        <td >
          <a href="{{lib.get_absolute_url}}">
            <span property="libns:library_id">{{ lib.id }}</span>
          </a>
        </td>
        <td rel="libns:species">
          <a typeof="libns:Species"
             href="{{ lib.library_species.get_absolute_url }}">
            <span property="libns:species_name">{{ lib.library_species.scientific_name }}</span>
          </a>
        </td>
        <td >
          <a href="{{ lib.get_absolute_url }}">
            <span property="libns:name">{{ lib.library_name }}</span>
          </a>
        </td>
        {% for ended in lib.lanes_sequenced %}
          {% cycle '#00BFFF' '#66CDAA' as bincolor silent %}
          {% for bin in ended %}
          <td bgcolor="{{ bincolor }}">{% if bin %}{{ bin }}{% endif %}</td>
          {% endfor %}
        {% endfor %}
        {% if lib.is_archived %}
          <td ><img src="{% static "img/hdd_unmount.png" %}" alt="Archived" /></td>
        {% else %}
          <td ></td>
        {% endif %}
      </tr>
      {% empty %}
      <tr><td colspan="0">No results found</td></tr>
      {% endfor %}
    </tbody>
  </table>
  </div>
  {% endblock %}
</div>
{% endblock %}

htsworkflow/templates/samples/species_detail.html
{% extends "base_site.html" %}
{% load static %}
{% load humanize i18n %}
{% block extrahead %}
    <!-- App Stuff -->
    <link type="text/css" rel="stylesheet" href="{% static "css/app.css" %}" />
    <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
    
    {% block additional_javascript %}
    {% endblock %}
{% endblock %}

{% block content %}
<div id="genome_detail">
  <h2>About this Genome</h2>
  <b>Common Name</b>: 
     <span property="libns:species_name">{{ species.common_name}}</span><br/>
  <b>Scientific Name</b>: 
     <span property="libns:species_name">{{ species.scientific_name}}</span><br/>
</div>  
{% endblock %}