bcmagic/urls.py
from __future__ import unicode_literals
from django.urls import path

from bcmagic.views import (
    json_test,
    magic,
    index,
)

urlpatterns = [
    path("", index, name="bcmagic_index"),
    path("json_test/", json_test, name="bcmagic_json_test"),
    path("magic/", magic, name="bcmagic_index"),
]

experiments/urls.py
from __future__ import unicode_literals

from django.urls import path

from .experiments import flowcell_json, lanes_for_json
from .views import (
    index,
    read_result_file,
    startedEmail,
    finishedEmail,
)

urlpatterns = [
    path("", index, name="flowcell_index"),
    # url(r'^liblist$', 'htsworkflow.frontend.experiments.views.test_Libs'),
    # url(r'^(?P<run_folder>.+)/$', 'gaworkflow.frontend.experiments.views.detail'),
    path("config/<fc_id>/json", flowcell_json, name="flowcell_config_json"),
    path("lanes_for/<username>/json", lanes_for_json, name="lanes_for_json"),
    path("file/<key>", read_result_file, name="read_result_file"),
    path("started/<pk>/", startedEmail, name="started_email"),
    path("finished/<pk>", finishedEmail, name="finished_email"),
]

ga_frontend/urls.py
from django.conf.urls.defaults import *

# Databrowser:
from django.contrib import databrowse
from fctracker.models import Library, FlowCell
databrowse.site.register(Library)
databrowse.site.register(FlowCell)

urlpatterns = patterns('',
    # Base:
    (r'^eland_config/', include('ga_frontend.eland_config.urls')),
    # Admin:
     (r'^admin/', include('django.contrib.admin.urls')),
    # Databrowser:
     (r'^databrowse/(.*)', databrowse.site.root),
)

htsworkflow/urls.py
from django.urls import include, path
from django.contrib import admin

from experiments.views import (
    FlowCellListView,
    flowcell_lane_detail,
    flowcell_detail,
    lanes_for,
    sequencer,
)
from samples.views import library_id_to_admin_url

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    # Base:
    path("eland_config/", include("eland_config.urls")),
    # Experiments:
    path("experiments/", include("experiments.urls")),
    path("lane/<lane_pk>", flowcell_lane_detail, name="flowcell_lane_detail"),
    path("flowcell/<flowcell_id>/", flowcell_detail, name="flowcell_detail"),
    path(
        "flowcell/<flowcell_id>/<lane_number>/",
        flowcell_detail,
        name="flowcell_detail",
    ),
    path("flowcell/", FlowCellListView.as_view(), name="flowcell_index"),
    path("inventory/", include("inventory.urls")),
    path("library/", include("samples.urls")),
    path("lanes_for/", lanes_for, name="lanes_for"),
    path("lanes_for/<username>", lanes_for, name="lanes_for"),
    ### library id to admin url
    path("library_id_to_admin_url/<library_id>/", library_id_to_admin_url),
    path("sequencer/<sequencer_id>", sequencer, name="sequencer"),
    path("admin/", admin.site.urls),
]

experiments/models.py
from __future__ import absolute_import, print_function, unicode_literals

import datetime
import glob
import logging
import os
import re
import uuid

from django.conf import settings
from django.urls import reverse
from django.utils import timezone
from django.db import models
from django.db.models.signals import pre_save

from samples.models import Library, HTSUser
from htsworkflow.util.conversion import parse_flowcell_id
from htsworkflow.pipelines import runfolder

try:
    from zoneinfo import ZoneInfo
except ImportError:
    from backports.zoneinfo import ZoneInfo


LOGGER = logging.getLogger(__name__)
default_pM = 5
try:
    default_pM = int(settings.DEFAULT_PM)
except AttributeError as e:
    LOGGER.error("invalid value for default_pm")

# how many days to wait before trying to re-import a runfolder
RESCAN_DELAY = 1
try:
    RESCAN_DELAY = int(settings.RESCAN_DELAY)
except (ValueError, AttributeError):
    LOGGER.error("Missing or invalid settings.RESCAN_DELAY, "\
                 "defaulting to %s" % (RESCAN_DELAY,))

RUN_STATUS_CHOICES = (
    (0, 'Sequencer running'),  # Solexa Data Pipeline Not Yet Started'),
    (1, 'Data Pipeline Started'),
    (2, 'Data Pipeline Interrupted'),
    (3, 'Data Pipeline Finished'),
    (4, 'Collect Results Started'),
    (5, 'Collect Results Finished'),
    (6, 'QC Started'),
    (7, 'QC Finished'),
    (255, 'DONE'),
  )
RUN_STATUS_REVERSE_MAP = dict(((v, k) for k, v in RUN_STATUS_CHOICES))


class ClusterStation(models.Model):
    """List of cluster stations"""
    name = models.CharField(max_length=50, unique=True)
    isdefault = models.BooleanField(default=False, null=False)

    class Meta:
        ordering = ["-isdefault", "name"]

    def __str__(self):
        return str(self.name)

    @staticmethod
    def update_isdefault(sender, instance, **kwargs):
        """Clear default if needed
        """
        if instance.isdefault:
            for c in ClusterStation.objects.filter(isdefault=True).all():
                if c.id != instance.id:
                    c.isdefault = False
                    c.save()

def cluster_station_default():
    d = ClusterStation.objects.filter(isdefault=True).all()
    if len(d) > 0:
        return d[0]
    d = ClusterStation.objects.order_by('-id').all()
    if len(d) > 0:
        return d[0]
    return None

pre_save.connect(ClusterStation.update_isdefault, sender=ClusterStation)

class Sequencer(models.Model):
    """Sequencers we've owned
    """
    name = models.CharField(max_length=50, db_index=True)
    instrument_name = models.CharField(max_length=50, db_index=True)
    serial_number = models.CharField(max_length=50, db_index=True)
    model = models.CharField(max_length=255)
    active = models.BooleanField(default=True, null=False)
    isdefault = models.BooleanField(default=False, null=False)
    comment = models.CharField(max_length=255)

    class Meta:
        ordering = ["-isdefault", "-active", "name"]

    def __str__(self):
        name = [str(self.name)]
        if self.instrument_name is not None:
            name.append("(%s)" % (str(self.instrument_name),))
        return " ".join(name)

    def get_absolute_url(self):
        return reverse('sequencer', kwargs={'sequencer_id': self.id})

    @staticmethod
    def update_isdefault(sender, instance, **kwargs):
        """Clear default if needed
        """
        if instance.isdefault:
            for s in Sequencer.objects.filter(isdefault=True).all():
                if s.id != instance.id:
                    s.isdefault = False
                    s.save()

pre_save.connect(Sequencer.update_isdefault, sender=Sequencer)

def sequencer_default():
    d = Sequencer.objects.filter(isdefault=True).all()
    if len(d) > 0:
        return d[0]
    d = Sequencer.objects.order_by('active', '-id').all()
    if len(d) > 0:
        return d[0]
    return None


class FlowCell(models.Model):
    flowcell_id = models.CharField(max_length=20, unique=True, db_index=True)
    run_date = models.DateTimeField()
    advanced_run = models.BooleanField(default=False)
    paired_end = models.BooleanField(default=False)
    read_length = models.IntegerField(default=32)  # Stanford is currenlty 25
    control_lane = models.IntegerField(choices=[(1, 1),
                                                (2, 2),
                                                (3, 3),
                                                (4, 4),
                                                (5, 5),
                                                (6, 6),
                                                (7, 7),
                                                (8, 8),
                                                (0, 'All Lanes')],
                                       null=True,
                                       blank=True)

    cluster_station = models.ForeignKey(ClusterStation,
                                        default=cluster_station_default,
                                        on_delete=models.CASCADE,
    )
    sequencer = models.ForeignKey(Sequencer, default=sequencer_default,
                                  on_delete=models.CASCADE,
    )

    notes = models.TextField(blank=True)

    def __str__(self):
        return str(self.flowcell_id)

    def Lanes(self):
        html = ['<table>']
        for lane in self.lane_set.order_by('lane_number'):
            cluster_estimate = lane.cluster_estimate
            if cluster_estimate is not None:
                cluster_estimate = "%s k" % ((int(cluster_estimate) / 1000), )
            else:
                cluster_estimate = 'None'
            library_id = lane.library_id
            library = lane.library
            element = '<tr><td>%d</td>'\
                      '<td><a href="%s">%s</a></td><td>%s</td></tr>'
            html.append(element % (lane.lane_number,
                                   library.get_admin_url(),
                                   library,
                                   cluster_estimate))
        html.append('</table>')
        return "\n".join(html)
    Lanes.allow_tags = True

    class Meta:
        ordering = ["-run_date"]

    def get_admin_url(self):
        # that's the django way... except it didn't work
        return reverse('admin:experiments_flowcell_change',
                       args=(self.id,))

    def flowcell_type(self):
        """Convert our boolean 'is paired' flag to a name
        """
        if self.paired_end:
            return "Paired"
        else:
            return "Single"

    def get_absolute_url(self):
        flowcell_id, status = parse_flowcell_id(self.flowcell_id)
        return reverse('flowcell_detail', args=[str(flowcell_id)])

    def get_raw_data_directory(self):
        """Return location of where the raw data is stored"""
        flowcell_id, status = parse_flowcell_id(self.flowcell_id)

        return os.path.join(settings.RESULT_HOME_DIR, flowcell_id)

    def update_sequencing_runs(self):
        result_root = self.get_raw_data_directory()
        LOGGER.debug("Update data runs flowcell root: %s" % (result_root,))
        if result_root is None:
            return

        run_xml_re = re.compile(glob.fnmatch.translate('run*.xml'))

        for dirpath, dirnames, filenames in os.walk(result_root):
            for filename in filenames:
                if run_xml_re.match(filename):
                    # we have a run directory
                    relative_pathname = get_relative_pathname(dirpath)
                    self.import_sequencing_run(relative_pathname, filename)

    def import_sequencing_run(self, relative_pathname, run_xml_name, force=False):
        """Given a result directory import files"""
        now = timezone.now()
        run_dir = get_absolute_pathname(relative_pathname)
        run_xml_path = os.path.join(run_dir, run_xml_name)

        runs = SequencingRun.objects.filter(result_dir = relative_pathname)
        if len(runs) == 0:
            run = SequencingRun()
            created = True
        elif len(runs) > 1:
            raise RuntimeError("Too many data runs for %s" % (
                relative_pathname,))
        else:
            run = runs[0]
            created = False

        if created or force or (now-run.last_update_time).days > RESCAN_DELAY:
            LOGGER.debug("Importing run from %s" % (relative_pathname,))
            run_xml_data = runfolder.load_pipeline_run_xml(run_xml_path)
            run.flowcell = self
            run.status = RUN_STATUS_REVERSE_MAP['DONE']
            run.result_dir = relative_pathname
            run.runfolder_name = run_xml_data.runfolder_name
            run.cycle_start = run_xml_data.image_analysis.start
            run.cycle_stop = run_xml_data.image_analysis.stop
            TZ = ZoneInfo(settings.TIME_ZONE)
            run.run_start_time = datetime.datetime(
                year=run_xml_data.image_analysis.date.year,
                month=run_xml_data.image_analysis.date.month,
                day=run_xml_data.image_analysis.date.day,
                tzinfo=TZ)
            run.image_software = run_xml_data.image_analysis.software
            run.image_version = run_xml_data.image_analysis.version
            run.basecall_software = run_xml_data.bustard.software
            run.basecall_version = run_xml_data.bustard.version
            # we're frequently not running alignments
            if run_xml_data.gerald:
                run.alignment_software = run_xml_data.gerald.software
                run.alignment_version = run_xml_data.gerald.version

            run.last_update_time = timezone.now()
            run.save()

            run.update_result_files()


# FIXME: should we automatically update sequencing run?
#        Or should we expect someone to call update_sequencing_runs?
#def update_flowcell_sequencingruns(sender, instance, *args, **kwargs):
#    """Update our sequencing rungs
#    """
#    if not os.path.exists(settings.RESULT_HOME_DIR):
#       return
#

trunk/htsworkflow/frontend/experiments/views.py
# Create your views here.
#from django.template import Context, loader
#shortcut to the above modules
from django.shortcuts import render_to_response, get_object_or_404
from htsworkflow.frontend.experiments.models import *
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist

def index(request):
    all_runs = DataRun.objects.order_by('-run_start_time')
    #t = loader.get_template('experiments/index.html')
    #c = Context({
    #    'data_run_list': all_runs,
    #})
    #return HttpResponse(t.render(c)) 
    # shortcut to the above module usage
    return render_to_response('experiments/index.html',{'data_run_list': all_runs}) 
    
def detail(request, run_folder):
    html_str = '<h2>Exp Track Details Page</h2>'
    html_str += 'Run Folder: '+run_folder
    r = get_object_or_404(DataRun,run_folder=run_folder)
    return render_to_response('experiments/detail.html',{'run_f': r})

def makeFCSheet(request,fcid):
  # get Flowcell by input fcid
  # ...
  rec = None
  try:
    rec = FlowCell.objects.get(flowcell_id=fcid)
  except ObjectDoesNotExist:
    pass
  lanes = ['1','2','3','4','5','6','7','8']
  return render_to_response('experiments/flowcellSheet.html',{'fc': rec})

experiments/templates/experiments/detail.html
{% if run_f %}
    <ul>
        RUN FOLDER:  <li>{{ run_f.run_folder }}</li>
    </ul>
{% else %}
    <p>Run folder not found.</p>
{% endif %}

experiments/templates/experiments/email_preview.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label='experiments' %}">sequencing runs</a>
&rsaquo; <a href="{% url 'admin:experiments_flowcell_changelist' %}">Flow Cells</a>
&rsaquo; <a href="{% url 'admin:experiments_flowcell_change' flowcell.pk %}">{{title}}</a>
</div>
{% endblock %}

{% block content %}
{% if warnings %}
<hr/>
<p>
{% for user_admin_url, username in warnings %}
Warning: User <a href="{{ user_admin_url}}">{{ username }}</a> has no
email address <br/>
{% endfor %}
{% endif %}
</p>
{% for to, subject, body, sending in emails %}
<hr/>
{% if sending %}<b>Message:</b> {{ sending }}<br/>{% endif %}
<b>From:</b> {{ from }}<br/>
<b>To:</b> {{ to }}<br/>
<b>Subject:</b> {{ subject }}<br/>
<pre>
{{ body }}
</pre>
{% endfor %}<hr/>
<form method="get">
<label for="bcc">BCC {% for m in site_managers %}{{ m }} {% endfor %}</label>
<input type="checkbox" id="bcc" name="bcc" checked="on"/><br/>
<input type="hidden" name="send" value="1"/>
<input type="submit" value="Send Email"/>
{% endblock %}

experiments/templates/experiments/flowcellSheet.html
<html><head><title>{{ fc.flowcell_id }} - GA SEQUENCING (SOLEXA) LOG</title>
<style type="text/css">
<!--
TD
  {
  color:black;
  font-size:9pt;
  font-face:Arial;
  }
-->
</style>
</head><body>
{% if fc %}
<table border="1" cellspacing="1">
<tr><td colspan=2 nowrap><b>GA SEQUENCING (SOLEXA) LOG</b></td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr><td>Date Run Started</td><td colspan=2>{{ fc.run_date }}</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr><td>Cluster station used</td><td colspan=2 nowrap>{{ fc.cluster_station.name }}</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr><td>GA used</td><td colspan=2 nowrap>{{ fc.sequencer.name }}</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>

<tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr><td>Flowcell number</td><td colspan=2 nowrap>{{ fc.flowcell_id }}</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr><td>Number of Tiles per Lane</td><td>100</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr><td>Number of Cycles</td><td>{{ fc.read_length  }}</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr><td><font point-size="9" face="Arial"><b>SAMPLE INFORMATION</b><font></td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr><td>&nbsp;</td><td>FC#</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td colspan=2 nowrap>FC bar code</td></tr>

<tr><td valign=middle nowrap>Lane</td>
{% for lane in fc.lane_set.all %}
<td>{{ lane.lane_number }}</td>
{% endfor %}
</tr>
<tr><td valign=middle nowrap>Solexa Library Number</td>
{% for lane in fc.lane_set.all %}
<td bgcolor=#CCFFCC>{{ lane.library.id }}</td>
{% endfor %}
</tr>

<tr><td valign=middle nowrap>Sample Name</td>
{% for lane in fc.lane_set.all %}
<td bgcolor=#CCFFCC>{{ lane.library.library_name }}</td>
{% endfor %}
</tr>

<tr><td valign=middle nowrap>Organism</td>
{% for lane in fc.lane_set.all %}
<td bgcolor=#CCFFCC>{{ lane.library.library_species.scientific_name }}</td>
{% endfor %}
</tr>

<tr><td valign=middle nowrap>Submitter</td>
{% for lane in fc.lane_set.all %}
<td bgcolor=#CCFFCC>{{ lane.library.made_for }}</td>
{% endfor %}
</tr>


<tr><td valign=middle nowrap>First time run?</td><td bgcolor=#CCFFCC></td><td bgcolor=#CCFFCC></td><td bgcolor=#CCFFCC></td><td bgcolor=#CCFFCC></td><td bgcolor=#CCFFCC></td><td bgcolor=#CCFFCC></td><td bgcolor=#CCFFCC></td><td bgcolor=#CCFFCC></td></tr>

<tr><td valign=middle nowrap>Gel Cut Size (bp)</td>
{% for lane in fc.lane_set.all %}
<td bgcolor=#CCFFCC>{{ lane.library.gel_cut_size }}</td>
{% endfor %}
</tr>	

<tr><td valign=middle nowrap>Template Concentration (ng/ul)</td>
{% for lane in fc.lane_set.all %}
<td bgcolor=#CCFFCC>{{ lane.library.undiluted_concentration }}</td>
{% endfor %}
</tr>

<tr><td valign=middle nowrap>Run Concentration (pM)</td>
{% for lane in fc.lane_set.all %}
<td bgcolor=#CCFFCC>{{ lane.pM }}</td>
{% endfor %}
</tr>

</table>

{% else %}
    <p>Flowcell object missing. Can't create sheet.</p>
{% endif %}

</body></html

experiments/templates/experiments/flowcell_detail.html
{% extends "base_site.html" %}
{% load static %}
{% load humanize i18n %}
{% block extrahead %}
    <!-- App Stuff -->
    <link type="text/css" rel="stylesheet" href="{% static "css/app.css" %}" />
    <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>

    {% block additional_javascript %}
    {% endblock %}
{% endblock %}

{% block content %}
<div>
  {% include "experiments/flowcell_header.html" %}
  <div class="htswdetail" typeof="libns:IlluminaFlowcell" resource="{{flowcell.get_absolute_url}}">
    <h2>Lanes</h2>
    <table>
      <thead>
       <tr>
         <td>Lane</td>
         <td>Library ID</td>
         <td>Library Name</td>
         <td>Species</td>
         <td>Comment</td>
         <td>Lane Status</td>
       </tr>
      </thead>
      <tbody>
      {% for lane in lanes %}
        <tr about="{{lane.get_absolute_url}}">
          <td about="{{flowcell.get_absolute_url}}" rel="libns:{{ lane.has_lane_term }}">
            <a href="{{lane.get_absolute_url}}" typeof="libns:IlluminaLane">
              <span property="libns:lane_number">{{lane.lane_number}}</span>
            </a>
          </td>
          <td rel="libns:library"
              resource="{{lane.library.get_absolute_url}}">
            <a typeof="libns:Library" href="{{lane.library.get_absolute_url}}">
              <span property="libns:library_id"
                    >{{lane.library.id}}</span></a>
              {% if user.is_staff %}
              <a href="{{lane.library.get_admin_url}}">
                  <img class="icon_button"
                       src="{% static "admin/img/icon-changelink.svg" %}"/>
              </a>{% endif %}
          </td>
          <td>
            <a href="{{lane.library.get_absolute_url}}">
              <span property="libns:name"
                    about="{{lane.library.get_absolute_url}}"
                    >{{lane.library.library_name}}</span>
            </a>
          </td>
          <td about="{{lane.library.get_absolute_url}}" rel="libns:species">
            <a href="{{lane.library.library_species.get_absolute_url}}"
               typeof="libns:Species">
              <span property="libns:species_name">{{ lane.library.library_species.scientific_name }}</span></a>
          </td>
          <td>
            <span property="libns:comment">{{lane.comment}}</span>
          </td>
          <td property="libns:status">{{ lane.status_name }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    <div class="htsw_flowcell_ivc">
    {% for run in flowcell.datarun_set.all %}
       <h2>Run {{ run.runfolder_name }}</h2>
       {% if run.lane_files %}
       <table>
         <thead>
           <tr>
             <td>Lane</td>
             <td>IVC All</td>
             <td>IVC Call</td>
             <td>IVC Percent Base</td>
             <td>IVC Percent Base All</td>
             <td>IVC Percent Base Called</td>
           </tr>
         </thead>
         <tbody>
            {% for lane_id, lane_file_set in run.lane_files.items %}
            {% if lane_file_set.ivc_all %}
            <tr>
              <td>{{ lane_id }}</td>
              <td>
                <a href="{{ lane_file_set.ivc_all.get_absolute_url }}">
                <img height="84" width="126" alt="Lane {{lane_id }} IVC All"
                     src="{{ lane_file_set.ivc_all.get_absolute_url }}"/></a>
              </td>
              <td>
                <a href="{{ lane_file_set.ivc_call.get_absolute_url }}">
                <img height="84" width="126" alt="Lane {{lane_id }} IVC Call"
                     src="{{ lane_file_set.ivc_call.get_absolute_url }}"/>
                </a>
              </td>
              <td>
                <a href="{{ lane_file_set.ivc_percent_base.get_absolute_url }}">
                <img height="84" width="126" alt="Lane {{lane_id }} IVC % Base"
                     src="{{ lane_file_set.ivc_percent_base.get_absolute_url }}"/>
                </a>
              </td>
              <td>
                <a href="{{ lane_file_set.ivc_percent_all.get_absolute_url }}">
                <img height="84" width="126" alt="Lane {{lane_id }} IVC % Base All"
                     src="{{ lane_file_set.ivc_percent_all.get_absolute_url }}"/>
                </a>
              </td>
              <td>
                <a href="{{ lane_file_set.ivc_percent_call.get_absolute_url }}">
                <img height="84" width="126"
                     alt="Lane {{lane_id }} IVC % Base Called"
                     src="{{ lane_file_set.ivc_percent_call.get_absolute_url }}"/>
                </a>
              </td>
            </tr>
            {% endif %}
            {% endfor %}
         </tbody>
       </table>
       {% endif %}
    {% endfor %}
    </div>
  </div>
</div>
<!-- end flowcell_detail -->
{% endblock %}

experiments/templates/experiments/flowcell_index.html
{% extends "base_site.html" %}
{% load htsworkflow %}
{% load static %}
{% block title %}Flowcell Index{% endblock %}
{% block extrahead %}
    <!-- App Stuff -->
    <link type="text/css" rel="stylesheet" href="{% static "css/app.css" %}"/>
{% endblock %}

{% block content %}
    {% pagination page_obj %}
    <table class="{% if flowcell_list.has_filters %} filtered {% endif %}">
      <thead>
        <tr>
          <td>Flowcell ID</td>
          <td>run_date</td>
          <td>notes</td>
        </tr>
      </thead>
      <tbody>
        {% for flowcell in flowcell_list %}
        <tr typeof="libns:IlluminaFlowcell" about="{{flowcell.get_absolute_url}}">
          <td><a href="{{flowcell.get_absolute_url}}">{{flowcell.flowcell_id}}</a></td>
          <td property="libns:date" content="{{flowcell.run_date|date:'Y-m-d\TH:i:s'}}" datatype="xsd:dateTime">{{flowcell.run_date}}</td>
          <td><span property="libns:flowcell_notes">{{flowcell.notes}}</span></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock %}    

experiments/templates/experiments/index.html
{% if data_run_list %}
    <table>
      {% for run in data_run_list %}
        <tr>
          <td>{{run.run_folder}}</td>
          <td><a href="fcsheet/{{run.fcid}}">sheet</td>
          <td><a href="started/{{run.fcid}}">started email</td>
          <td><a href="finished/{{run.fcid}}">finished email</td>
       </tr>
      {% endfor %}
   </table>
{% else %}
    <p>No data runs are available.</p>
{% endif %}